[programs.localnet]
ticketing_system = "FnBX9ffS8oWYMaW8FVdnzrfuWAhhKo5RFWugMH6hAYuk"

[programs.testnet]
ticketing_system = "FnBX9ffS8oWYMaW8FVdnzrfuWAhhKo5RFWugMH6hAYuk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/Users/fmendez/.config/solana/id.json"

[scripts]
# test = "yarn run mocha -t 1000000 tests/"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
